name: CI on push
on:
  push:
    paths:
      - 'hello-world/**'
      - '!hello-world/README.md'
      - '.github/workflows/hello-world.yaml'
jobs:
  build:
    runs-on: ubuntu-latest
    env:   
      EXREPO: acap-computer-vision-examples-sandbox
      EXNAME: hello-world    
      WORKDIR: acap-computer-vision-sdk-examples-sandbox\hello-world
    strategy:
      matrix:
        include:
          - arch: aarch64
          # - arch: armv7hf

    steps: 
      - uses: actions/checkout@v2
      - name: Loop for spending time.
        run: | 
          for i in {1..5}; do
              sleep 1
              echo $i
          done
      - name: test to get architecture on another camera
        run: | 
          ok=$(curl -v -s --noproxy '*' --anyauth -u root:"pass" -k --header "Content-Type: application/json" --request POST --data '{"apiVersion":"1.0","method":"getProperties", "params": {"propertyList": ["Architecture"]}}' http://172.25.65.98/axis-cgi/basicdeviceinfo.cgi)
          echo  "response from curl= $ok" 
          ok=${ok#*Architecture}
          echo "test=$(echo $ok | cut -d '"' -f 3)" >> $GITHUB_ENV
          echo ok=$(echo $ok | cut -d '"' -f 3)

          ok=$(curl -v -s --noproxy '*' --anyauth -u root:"pass" -k --header "Content-Type: application/json" --request POST --data '{"apiVersion":"1.0","method":"getProperties", "params": {"propertyList": ["Architecture"]}}' http://172.25.70.46/axis-cgi/basicdeviceinfo.cgi)
          echo  "response from curl= $ok" 
          ok=${ok#*Architecture}
          echo "test=$(echo $ok | cut -d '"' -f 3)" >> $GITHUB_ENV
          echo ok=$(echo $ok | cut -d '"' -f 3) 
              