name: Build hello-world application

on:
  push:
    paths:
      - 'hello-world/**'
      - '!hello-world/README.md'
      - '.github/workflows/hello-world.yaml'
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    env:   
      EXREPO: acap-computer-vision-examples
      EXNAME: hello-world
      EAPNAME: hello_world      
      EXDIR: acap/examples/$EXNAME 
    strategy:
      matrix:
        include:
          - arch: aarch64
          # - arch: armv7hf
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: can i reach the camera
        run: |
          ping 172.25.65.98
      # - name: Get the architecture from the camera
      #   run: |
      #     ok=$(curl -v -s --noproxy '*' --anyauth -u root:"pass" -k --header "Content-Type: application/json" --request POST --data '{"apiVersion":"1.0", "method":"getProperties", "params": {"propertyList": ["Architecture"]}}' http://172.25.65.98/axis-cgi/basicdeviceinfo.cgi)
      #     echo  "response from curl= $ok" 
      #     ok=${ok#*Architecture}
      #     echo "test=$(echo $ok | cut -d '"' -f 3)" >> $GITHUB_ENV
      #     echo ok=$(echo $ok | cut -d '"' -f 3)

      # - name: Test the env variable  
      #   id: InfoId
      #   run: | 
      #     echo $test 

      - name: Build ${{ env.example }} application
        env:
          example: ${{ env.EXNAME }}
          imagetag: ${{ env.EXREPO }}_${{ env.EXNAME }}:1.0
        run: |
          cd $EXNAME
          docker build --no-cache --build-arg ARCH=${{ matrix.arch }} --tag $imagetag .
      

      


        