name: Build hello-world application
on: 
  push: 
    paths:  
      - 'hello-world/**'
      - '!hello-world/README.md'
      - '.github/workflows/hello-world.yaml'
  pull_request:
    types: [opened, synchronize]
    
jobs:  
  build:
    runs-on: self-hosted 
    env:   
      EXREPO: acap-computer-vision-examples-sandbox
      EXNAME: hello-world    
      WORKDIR: acap-computer-vision-sdk-examples-sandbox\hello-world
    strategy:
      matrix:
        include:   
          - arch: aarch64   # for arm64
          # - arch: armv7hf   # for arm32
    steps:   
      - uses: actions/checkout@v2
      - name: Build the image.
        env:  
          arch: "aarch64"
        run: |
          echo $(pwd)
          cd /home/fadelb/actions-runner/_work/acap-computer-vision-sdk-examples-sandbox/acap-computer-vision-sdk-examples-sandbox/hello-world
          echo $(pwd)
          docker build --tag hello-world --build-arg aarch64 .
          ls app/

      - name: Set your device IP address and clear Docker memory.
        run: |
          docker --tlsverify --host tcp://172.25.65.98:2376 system prune --all --force

      - name: load hello-world application.
        run: |
          docker save hello-world | docker -v --tlsverify --host tcp://172.25.65.98:2376 load