name: CI AND PUSH 
on:
  push: [main]
jobs:
  build:
    runs-on: self-hosted 
    env:   
      EXREPO: acap-computer-vision-examples-sandbox
      EXNAME: hello-world    
      WORKDIR: acap-computer-vision-sdk-examples-sandbox\hello-world
    strategy:
      matrix:
        include:   
          - arch: aarch64
          # - arch: armv7hf
 
    steps: 
      - uses: actions/checkout@v2
      - name: just loop
        run: |
          for i in {1..5},do
                slepp(1)  
              return i 

