name: CI AND PUSH 
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted 
    env:   
      EXREPO: acap-computer-vision-examples-sandbox
      EXNAME: hello-world    
      WORKDIR: acap-computer-vision-sdk-examples-sandbox\hello-world
    strategy:
      matrix:
        include:   
          - arch: aarch64
          # - arch: armv7hf
 
    steps: 
      - uses: actions/checkout@v2
      - name: just loop
        run: |
          for ($i=1; $i -le 5; $i++) {
            Start-Sleep -Seconds 1
            Write-Output $i
          }
    
      - name:  get the architecture
        run: |
          ok=$(curl -v -s --noproxy '*' --anyauth -u root:"pass" -k --header "Content-Type: application/json" --request POST --data '{"apiVersion":"1.0","method":"getProperties", "params": {"propertyList": ["Architecture"]}}' http://172.25.65.98/axis-cgi/basicdeviceinfo.cgi)
          echo  "response from curl= $ok" 
          ok=${ok#*Architecture}
          echo "test=$(echo $ok | cut -d '"' -f 3)" >> $GITHUB_ENV
          echo ok=$(echo $ok | cut -d '"' -f 3)

# name: Check Runner Access

# on: [push]

# jobs:
#   check_access:
#     runs-on: self-hosted
#     steps:
#       - name: Test Connection
#         run: |
#           curl -v https://github.com/nodeFade

