name: threat-modeling
on:
  push: 
    paths:  
      - '.github/workflows/hello-world.yaml'
      - '.github/workflows/threat-model-test.yaml'

jobs:       
  build:
    runs-on: self-hosted  
    container:
      image: python:3.9 
    env:   
      EXREPO: acap-computer-vision-examples-sandbox 
      WORKDIR: acap-computer-vision-sdk-examples-sandbox
    strategy:
      matrix:
        include:   
          - arch: aarch64
          # - arch: armv7hf  

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd "$GITHUB_WORKSPACE"
          sudo apt-get update && sudo apt-get install python3.9 -y
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install requests
          pip install paramiko

      - name: Run the python file with secret credentials.
        run: |
          python $GITHUB_WORKSPACE/threatCases.py ${{ secrets.DEVICE_IP }} ${{ secrets.ROOT_USERNAME}} ${{ secrets.ROOT_PASSWORD }} ${{ secrets.USER_USERNAME }} ${{ secrets.USER_PASSWORD }} ${{ secrets.OPERATOR_USERNAME }}  ${{ secrets.OPERATOR_PASSWORD }}  
        env:
          PYTHONUNBUFFERED: 1 
 