name: threat-modeling
on:
  push: 
    paths:  
      - 'acap/**'
      - '.github/workflows/acap.yaml'
      - '.github/workflows/hello-world.yaml'
      - '.github/workflows/threat-model-test.yaml'

jobs:    
  build:
    runs-on: self-hosted
    container:
      image: python:3.9
    env:   
      EXREPO: acap-computer-vision-examples-sandbox 
      WORKDIR: acap-computer-vision-sdk-examples-sandbox
    strategy:
      matrix:
        include:   
          - arch: aarch64
          # - arch: armv7hf  

    steps:    
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd "$GITHUB_WORKSPACE"
          sudo apt-get update && sudo apt-get install python3.9 -y
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install requests
          pip list

      - name: test the device as an attacker
        env:
          WORKDIR: acap-computer-vision-sdk-examples-sandbox
        run: |
          echo ${pwd}
          ls
          python $GITHUB_WORKSPACE/create-token.py ${{secrets.cam_password}} ${{secrets.cam_username}} ${{secrets.url_base}}
